Just as an eample, ML looks at a lot of data and then tries to predict properties of unknown data.

This is a supervised learning example.

SML can be split into two categories: classifications (what something is) and regression (how much something is).

In [1]:
from sklearn import datasets

iris = datasets.load_iris()
digits = datasets.load_digits()

# Remember these are not Pandas datasets. So you cannot manipulate them yet.

In [2]:
# import pandas as pd
# iris_df = pd.DataFrame(iris)
# iris_df.head()

# Did not work - > ValueError: arrays must all be same length

In [3]:
# This shows the data in the dataset we're trying to look at
print digits.data, "\n", iris.data

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]] 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5

In [4]:
digits.images[0]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [5]:
# So the first thing we're going to do is learn ... and then we PREDICT.
# For that we use SVC. Same thing we used on the Titanic example

from sklearn import svm

# clf is the classifier, or the thing that is going to be doing the learning.
clf = svm.SVC(gamma = 0.001, C=100)

# Right now gamma is set manually, but we could use grid search or cross 
# validation to find the correct gamma.

# More on the above here:
# http://scikit-learn.org/stable/modules/grid_search.html#grid-search
# http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation

In [6]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
# Now we: have the model and fitted the model.
# We can now LEARN from the model.

clf.predict(digits.data[-1])

/Users/robertdefilippi/miniconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([8])

In [8]:
# Lets take a look at k-means clustering.

from sklearn import cluster, datasets
iris = datasets.load_iris()

In [9]:
iris

{'DESCR': 'Iris Plants Database\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n

In [10]:
X_iris = iris.data
y_iris = iris.target

# print X_iris, "\n", y_iris

In [11]:
# Now we are going to find some clusters
# You can get the KMeans function from cluster
k_means = cluster.KMeans(n_clusters = 3)

# Fit it to our data
k_means.fit(X_iris)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=3, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=None, tol=0.0001,
    verbose=0)

In [12]:
# Now lets compare
print(k_means.labels_[::10])

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [13]:
print(y_iris[::10])

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


The same as the titanic problem, we can use a confusion matrix to see how good our predictions were.

In [16]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
X, y = iris.data, iris.target
clf = KNeighborsClassifier(n_neighbors=1)
clf.fit(X, y)
y_pred = clf.predict(X)

print(np.all(y == y_pred)), "\n"

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y, y_pred))

True 

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


The output of the matrix above is actual on the left, and predicted on the top. So with this model there was PERFECT prediction. But remember, this is not correct as we need to split things between trianing and testing.

In [17]:
from sklearn.cross_validation import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)

print(confusion_matrix(ytest, ypred))

[[ 8  0  0]
 [ 0 11  1]
 [ 0  0 18]]


Ohhh ... not as good, eh?

In [21]:
%run fig_code/svm_gui.py


Libsvm GUI

A simple graphical frontend for Libsvm mainly intended for didactic
purposes. You can create data points by point and click and visualize
the decision region induced by different kernels and parameter settings.

To create positive examples click the left mouse button; to create
negative examples click the right button.

If all examples are from the same class, it uses a one-class SVM.


fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the model
fit the m

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/robertdefilippi/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/Users/robertdefilippi/Google Drive/Programming/data-science-ipython-notebooks/fig_code/svm_gui.py", line 87, in fit
    X = train[:, 0:2]
IndexError: too many indices for array
